---
title: "Employment Sterling"
author: "Abdullah Rizwan"
date: '2022-06-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidycensus)
library(viridis)
```

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyverse)
sterling <- read_excel("C:/Users/abdul/Downloads/DSPG/Employmentsterling.xlsx",skip=2,col_names=TRUE)
subset_sterling <- sterling[103:127,c(1, 2:5)]
subset_sterling$`EMPLOYMENT STATUS`
subset_sterling$Label <- as.factor(subset_sterling$`EMPLOYMENT STATUS`)
```
```{r}
sterling$...2[103:127]
health_estimate <- sterling$...2[103:127]
health_estimate<- as.numeric(gsub(",", "", health_estimate))
health_name <- subset_sterling$`EMPLOYMENT STATUS`
#summed_edu <- subset_sterling %>% 
 # group_by(`EMPLOYMENT STATUS`) %>%
  #summarize(edu_sum = sum(employment_estimate))
#summed_edu1 <- summed_edu[-(10:15),]
```

```{r}
ggplot(subset_sterling, aes(x = `EMPLOYMENT STATUS`, y = ...4, fill = `EMPLOYMENT STATUS`))+geom_col()+theme(axis.text.x = element_text(angle=30))
```

```{r}

 ggplot(subset_sterling,aes(health_name, health_estimate, fill=health_name)) + geom_col() +
   theme(axis.text.x = element_text(angle=90)) + coord_polar() + scale_y_log10()
```
bar graph for health insurance 
```{r}
subset_sterling <- sterling[c(103:105),]
subset_sterling$...4 <- as.numeric(gsub("%", "", subset_sterling$...4) )
subset_sterling$`EMPLOYMENT STATUS` <- reorder(subset_sterling$`EMPLOYMENT STATUS`, subset_sterling$...4)
health <- ggplot(subset_sterling, aes(x =`EMPLOYMENT STATUS`,y = (subset_sterling$...4), fill = `EMPLOYMENT STATUS`)) + geom_bar(position = "stack", stat="identity", width = 0.5, aes(text = paste0(...4, "%"))) + labs(x = "Insurance Type", y= "Percentage", caption = " Source : DP03 ACS 5 -yr data 2016-2020", titlel = "Distribution of Health Insurance") + guides(fill = guide_legend(title = ""))+ theme(axis.text.y = element_text(angle=0), axis.ticks.y= element_blank())+ coord_flip()#
#+ scale_y_continuous(limits = c(0,100))

#ggplot(health,aes(x=Position))+geom_bar(binwidth=1)
#health <- factor(subset_sterling$`EMPLOYMENT STATUS`, levels = c("No coverage", "Public", "Private"))

ggplotly(health, tooltip = c("text"))
```



```{r}
# library(plotly)
# 
# fig <- plot_ly(
#   x = c("No coverage", "Public", "Private"),
#   y = c(16.5, 23.1, 68.2), 
#   name = "",
#   sort = TRUE,
#   type = "funnelarea",
#   textinfor = "percent"
# )
# 
# fig
```

The bar graph shows that the greatest percentage of population in the sterling area have private insurance. There is only a small percentage of 16.5% that do not have any health insurance coverage. Private insurance is more common in the population compared to public health insurance.