---
title: "Median Income"
author: "Amanda E. Ljuba"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
read_excel("incomemedian.xlsx")
medianin <- read_excel("incomemedian.xlsx")
```

```{r}
subset_medianin <- medianin[4:13, 1:5]
subset_medianin
mi_pop <- subset_medianin$...4
mi_cat <- subset_medianin$...1
```

```{r}
mi_cat.fac <- factor(mi_cat, levels = c(mi_cat))

ggplot(subset_medianin,aes(x=mi_cat.fac,y=mi_pop, fill=mi_cat.fac))+geom_col(stat="identity")+theme(axis.text.x=element_blank(),axis.text.y = element_blank(),axis.ticks.y=element_blank())+scale_x_discrete(limits=mi_cat.fac)+labs(title="Population by Income of Sterling, VA",subtitle="2016-2020",caption= "Source: S1901 ACS data 2016-2020",x="Income Level",y="Estimated Percent of Population",) + coord_polar() + guides(fill = guide_legend(title = "Income Level")) 
```
The largest income level within the population of the Sterling CPD is the $35,000 to $49,999 bracket followed closely by the $25,000 to $34,999 bracket. The smallest income levels within the population of the Sterling CPD are the brackets less than $10,000 and $10,000 to $14,999 followed by the bracket $15,000 to $24,999.
