---
title: "Sterling,VA Commuter Time"
author: "NDP"
date: '2022-06-13'
output: html_document
---

```{r set_up_API, }
readRenviron("~/.Renviron") #readin Census API key
Sys.getenv("CENSUS_API_KEY") #confirm you have read in your Census API key
```

```{r}
library(tidycensus)
# Set a year of interest
this.year = 2020

# This looks at the 5 year estimates
# You can also do "acs1"
vars <- load_variables(year = 2019,
                      dataset = "acs5",
                      cache = TRUE)
```

#Pie chart for commuter times of population
```{r}
# Create data for the graph.
commute_percentages <-  c(6.0, 18.0, 16.9, 13.2, 4.8, 13.1, 7.1, 10.2, 10.8)
labelsCT <-  c("Less than 10 minutes","10 to 14 minutes","15 to 19 minutes","20 to 24 minutes", "25 to 29 minutes", "30 to 34 minutes", "35 to 44 minutes", "45 to 59 minutes", "60 or more minutes")

piepercentCT <- round(100*commute_percentages/sum(commute_percentages), 1)

# Give the chart file a name.
png(file = "Commuter_Time.csv")

# Plot the chart.
pie(commute_percentages, labels = piepercentCT, main = "Commuter Time pie chart", sub = "Source: S0801 ACS data 2016-2020", col = rainbow(length(commute_percentages)))
legend("topright", c("Less than 10 minutes","10 to 14 minutes","15 to 19 minutes","20 to 24 minutes", "25 to 29 minutes", "30 to 34 minutes", "35 to 44 minutes", "45 to 59 minutes", "60 or more minutes"), cex = 0.8,
   fill = rainbow(length(commute_percentages)))
```

