---
title: "Visualization of Resources"
author: "Amanda E. Ljuba"
date: '2022-06-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(maps)
library(plotly)
library(DT)
library(dplyr)
library(tigris)
library(tidyverse)
library(tidycensus)
library(readxl)
library(collapsibleTree)
library(shinycssloaders)
library(leaflet)
library(leaflet.extras)
library(rvest)
library(sf)
library(shinydashboard)
library(shinydashboardPlus)
library(tidygeocoder)
library(janitor)
library(dplyr)
library(ggplot2)
library(magrittr)
options(tigris_use_cache = TRUE)
```

```{r}
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_API_KEY")
```

```{r}
blocks<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 2, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 2, Census Tract 6112.04, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.04, Loudoun County, Virginia",
"Block Group 2, Census Tract 6115.02, Loudoun County, Virginia",
"Block Group 3, Census Tract 6115.02, Loudoun County, Virginia",
"Block Group 1, Census Tract 6113, Loudoun County, Virginia",
"Block Group 2, Census Tract 6113, Loudoun County, Virginia",
"Block Group 3, Census Tract 6113, Loudoun County, Virginia",
"Block Group 1, Census Tract 6114, Loudoun County, Virginia",
"Block Group 2, Census Tract 6114, Loudoun County, Virginia",
"Block Group 3, Census Tract 6114, Loudoun County, Virginia",
"Block Group 1, Census Tract 6117.01, Loudoun County, Virginia",
"Block Group 2, Census Tract 6117.01, Loudoun County, Virginia",
"Block Group 1, Census Tract 6116.02, Loudoun County, Virginia",
"Block Group 2, Census Tract 6116.02, Loudoun County, Virginia",
"Block Group 1, Census Tract 6116.01, Loudoun County, Virginia",
"Block Group 2, Census Tract 6116.01, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.02, Loudoun County, Virginia")
va20_2 <- get_acs(geography = "block group",
                variables = c(hispanic = "B03002_012"),
                state = "VA",
                year = 2020,
                geometry = TRUE) %>%
filter(NAME %in% blocks)
```

```{r}
blocks_CDP<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 2, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.05, Loudoun County, Virginia",
"Block Group 2, Census Tract 6112.04, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.04, Loudoun County, Virginia",
"Block Group 2, Census Tract 6115.02, Loudoun County, Virginia",
"Block Group 3, Census Tract 6115.02, Loudoun County, Virginia",
"Block Group 1, Census Tract 6113, Loudoun County, Virginia",
"Block Group 2, Census Tract 6113, Loudoun County, Virginia",
"Block Group 3, Census Tract 6113, Loudoun County, Virginia",
"Block Group 1, Census Tract 6114, Loudoun County, Virginia",
"Block Group 2, Census Tract 6114, Loudoun County, Virginia",
"Block Group 3, Census Tract 6114, Loudoun County, Virginia",
"Block Group 1, Census Tract 6117.01, Loudoun County, Virginia",
"Block Group 2, Census Tract 6117.01, Loudoun County, Virginia",
"Block Group 1, Census Tract 6116.02, Loudoun County, Virginia",
"Block Group 2, Census Tract 6116.02, Loudoun County, Virginia",
"Block Group 1, Census Tract 6116.01, Loudoun County, Virginia",
"Block Group 2, Census Tract 6116.01, Loudoun County, Virginia",
"Block Group 3, Census Tract 6112.02, Loudoun County, Virginia")
va_20_CDP <- va20_2 %>% filter (NAME %in% blocks_CDP)
```

```{r}
map <- read_excel("school_locations.xlsx")
map$Longitude <- as.numeric(map$Longitudes)
map$Latitude <- as.numeric(map$Latitudes)

total <- merge(va20_2,map)

#specify the bin breaks
mybins <- c(0,300,600,900,1200,1500,1800,2100)
#specify the default color
mypalette <- colorBin(palette="inferno", domain=va20_2$estimate, na.color="transparent", bins=mybins)

leaflet(data = total) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~mypalette(va20_2$`estimate`),
    stroke=TRUE,
    weight = 1,
    smoothFactor = 0.2,
    opacity = 1.0,
    fillOpacity = 0.7, 
    label=paste("County: ",va20_2$GEOID, ", Value: ",va20_2$estimate),
    highlightOptions = highlightOptions(color = "white",
                                        weight = 2,
                                        bringToFront = TRUE)) %>% 
    addPolygons(data=)
  addLegend(pal=mypalette, position = "bottomright",
            values = ~va20_2$estimate,
            opacity = 0.5, title = "Hispanic Population") %>%
  addMarkers( ~Longitude, ~Latitude, popup = ~as.character(Address), label = ~as.character(School), labelOptions = TRUE)
```


```{r}
map <- read_excel("HealthandSocialServices.xlsx", sheet = "Food")
map$Longitude <- as.numeric(map$Longitude)
map$Latitude <- as.numeric(map$Latitude)

icon <- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "red")

icon2<- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "purple")

icon3 <- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "forestgreen")

leaflet(data = map) %>% addTiles() %>%
  addPolygons(data = va20_2,
color="yellow",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5,color=~pal(map)) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location),color=~pal(map)) %>% addPolygons(data = va_20_CDP,
color="red",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location)) %>% 
  
# Plot it
#library(ggplot2)
#ggplot() +
  #geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  #theme_void() 
``` 

use color factor

```{r}
map <- read_excel("HealthandSocialServices.xlsx", sheet = "Clothing")
map$Longitude <- as.numeric(map$Longitude)
map$Latitude <- as.numeric(map$Latitude)

leaflet(data = map) %>% addTiles() %>%
  addPolygons(data = va20_2,
color="yellow",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location)) %>% addPolygons(data = va_20_CDP,
color="red",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location)) 
# Plot it
#library(ggplot2)
#ggplot() +
  #geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  #theme_void() 
``` 

```{r}
map <- read_excel("HealthandSocialServices.xlsx", sheet = "Healthcare")
map$Longitude <- as.numeric(map$Longitude)
map$Latitude <- as.numeric(map$Latitude)

leaflet(data = map) %>% addTiles() %>%
  addPolygons(data = va20_2,
color="yellow",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location)) %>% addPolygons(data = va_20_CDP,
color="red",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Location), label = ~as.character(Location)) 
# Plot it
#library(ggplot2)
#ggplot() +
  #geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  #theme_void() 
``` 



```{r}
map1 <- read_excel("HealthandSocialServices.xlsx",sheet=1)

map2 <- read_excel("HealthandSocialServices.xlsx",sheet=2)

map3 <- read_excel("HealthandSocialServices.xlsx",sheet=3)

map1$Longitude <- as.numeric(map1$Longitude)
map1$Latitude <- as.numeric(map1$Latitude)
map2$Longitude2 <- as.numeric(map2$Longitude)
map2$Latitude2 <- as.numeric(map2$Latitude)
map3$Longitude3 <- as.numeric(map3$Longitude)
map3$Latitude3 <- as.numeric(map3$Latitude)

maps <- merge(map1,map2,map3)

icon <- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "red")

icon2<- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "purple")

icon3 <- awesomeIcons(icon = 'ios-close',
  iconColor = 'black',
  library = 'fa',
  markerColor = "green")

map <- read_excel("HealthandSocialServices.xlsx")

leaflet(data = maps) %>% addTiles() %>%
  addPolygons(data = va20_2,
color="yellow",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>% addPolygons(data = va_20_CDP,
color="red",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
   addAwesomeMarkers(~Longitude, ~Latitude, popup = ~as.character(Description), label = ~as.character(Location), icon=icons,data=map1) %>%
  addAwesomeMarkers(~Longitude2, ~Latitude2, popup = ~as.character(Description), label = ~as.character(Location), icon=icons2,data=map2) %>%
    addAwesomeMarkers(~Longitude3, ~Latitude3, popup = ~as.character(Description), label = ~as.character(Location), icon=icons3,data=map3)
```

