---
title: "Sterling"
author: "Nandini Das"
date: '2022-06-07'
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
    theme: readable
  pdf_document:
    toc: yes
    toc_depth: '4'
colorlinks: yes
urlcolor: blue
linkcolor: blue
citecolor: blue
anchorcolor: blue
toccolor: blue
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(shiny)
library(shinythemes)
library(shinyjs)
library(ggplot2)
library(maps)
library(plotly)
library(DT)
library(dplyr)
library(tigris)
library(tidyverse)
library(tidycensus)
library(readxl)
library(collapsibleTree)
library(shinycssloaders)
library(leaflet)
library(leaflet.extras)
library(rvest)
library(sf)
library(shinydashboard)
library(shinydashboardPlus)
library(tidygeocoder)
library(janitor)
library(dplyr)
library(ggplot2)
library(magrittr)
options(tigris_use_cache = TRUE)

library(rstudioapi)
setwd(dirname(getActiveDocumentContext()$path))
```

```{r set_up_API, }
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_API_KEY")
```

```{r}
blocks<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.04, Loudoun County, Virginia", "Block Group 2, Census Tract 6115.02, Loudoun County, Virginia","Block Group 3, Census Tract 6115.02, Loudoun County, Virginia", "Block Group 1, Census Tract 6113, Loudoun County, Virginia","Block Group 2, Census Tract 6113, Loudoun County, Virginia","Block Group 3, Census Tract 6113, Loudoun County, Virginia", "Block Group 1, Census Tract 6114, Loudoun County, Virginia","Block Group 2, Census Tract 6114, Loudoun County, Virginia","Block Group 3, Census Tract 6114, Loudoun County, Virginia","Block Group 1, Census Tract 6117.01, Loudoun County, Virginia","Block Group 2, Census Tract 6117.01, Loudoun County, Virginia", "Block Group 1, Census Tract 6116.02, Loudoun County, Virginia","Block Group 2, Census Tract 6116.02, Loudoun County, Virginia","Block Group 1, Census Tract 6116.01, Loudoun County, Virginia", "Block Group 2, Census Tract 6116.01, Loudoun County, Virginia")

va20_2 <- get_acs(geography = "block group",
                variables = c(hispanic = "B03002_012"),
                state = "VA",
                year = 2020,
                geometry = TRUE) %>%
filter(NAME %in% blocks)
```

```{r}

blocks_CDP<-c("Block Group 2, Census Tract 6115.02, Loudoun County, Virginia","Block Group 3, Census Tract 6115.02, Loudoun County, Virginia", "Block Group 1, Census Tract 6113, Loudoun County, Virginia","Block Group 2, Census Tract 6113, Loudoun County, Virginia","Block Group 3, Census Tract 6113, Loudoun County, Virginia", "Block Group 1, Census Tract 6114, Loudoun County, Virginia","Block Group 2, Census Tract 6114, Loudoun County, Virginia","Block Group 3, Census Tract 6114, Loudoun County, Virginia","Block Group 1, Census Tract 6117.01, Loudoun County, Virginia","Block Group 2, Census Tract 6117.01, Loudoun County, Virginia", "Block Group 1, Census Tract 6116.02, Loudoun County, Virginia","Block Group 2, Census Tract 6116.02, Loudoun County, Virginia","Block Group 1, Census Tract 6116.01, Loudoun County, Virginia","Block Group 2, Census Tract 6116.01, Loudoun County, Virginia")

va_20_CDP <- va20_2 %>% filter (NAME %in% blocks_CDP)

```



```{r}

map <- read_excel("/Users/nandinidas/Desktop/2022_DSPG_Loudoun/data/school_locations.xlsx")

map$Longitude <- as.numeric(map$Longitude)
map$Latitude <- as.numeric(map$Latitude)


# Show first 20 rows from the `quakes` dataset
leaflet(data = map) %>% addTiles() %>%
  addPolygons(data = va20_2,
color="yellow",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Address), label = ~as.character(Address)) %>% addPolygons(data = va_20_CDP,
color="red",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5) %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Address), label = ~as.character(School)) 


# Plot it
#library(ggplot2)
#ggplot() +
  #geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  #theme_void() 
```


```{r}
library(rgdal)
library(ggplot2)
library(sf)

my_spdf <- readOGR( 
  dsn= paste0(getwd(),"/data/tl_2021_51_elsd.shp"))

library(tools)
r1_gdb <- file_path_as_absolute("/Users/nandinidas/Desktop/2022_DSPG_Loudoun/data/tl_2021_51_elsd.shp")

chi_shape <- st_read("/Users/nandinidas/Desktop/2022_DSPG_Loudoun/data/tl_2021_51_elsd.shx")


r1_lyrlist <- ogrListLayers(r1_gdb)

```
{
```{r}
require(rgdal)
sugarland <- st_read(dsn = "/Users/nandinidas/Desktop/2022_DSPG_Loudoun/Sugarland_Elementary_AZ", "SugarL_ES_AZ", stringsAsFactors = FALSE)

length(sugarland)

summary(shape@data)

#shape$INTPTLAT <- as.numeric(shape$INTPTLAT)
#shape$INTPTLON <- as.numeric(shape$INTPTLON)

shapemap <- ggplot() + geom_polygon(data = shape, aes(x = "INTPTLON", y = "INTPTLAN"), colour = "black", fill = NA)

shape 

par(mar=c(0,0,0,0))
plot(shapemap, col="#f2f2f2", bg="skyblue", lwd=0.25, border=0 )

#shp_df <- broom::tidy(shapemap, region = "")
#lapply(shp_df, class)

#ggplot() + 
  #geom_sf(data = shapemap, size = 3, color = "black", fill = "cyan1") + 
  #ggtitle("AOI Boundary Plot") + 
  #coord_sf()

#shape
```

```{r}
par(mar=c(0,0,0,0))
plot(sugarland, col="#f2f2f2", bg="skyblue", lwd=0.25, border=0 )
```

```{r}
library(plotly)

fig <- plot_ly(
    type = 'scatterpolar',
    mode = 'lines'
  ) 
fig <- fig %>%
  add_trace(
    r = c(0, 1.5, 1.5, 0, 2.5, 2.5, 0),
    theta = c(0, 10, 25, 0, 205, 215, 0),
    fill = 'toself',
    fillcolor = '#709Bff',
    line = list(
      color = 'black'
    )
  ) 
fig <- fig %>%
  add_trace(
    r = c(0, 3.5, 3.5, 0),
    theta = c(0, 55, 75, 0),
    fill = 'toself',
    fillcolor = '#E4FF87',
    line = list(
      color = 'black'
    )
  ) 
fig <- fig %>%
  add_trace(
    r = c(0, 4.5, 4.5, 0, 4.5, 4.5, 0),
    theta = c(0, 100, 120, 0, 305, 320, 0),
    fill = 'toself',
    fillcolor = '#FFAA70',
    line = list(
      color = 'black'
    )
  ) 
fig <- fig %>%
  add_trace(
    r = c(0, 4, 4, 0),
    theta = c(0, 165, 195, 0),
    fill = 'toself',
    fillcolor = '#FFDF70',
    line = list(
      color = 'black'
    )
  ) 
fig <- fig %>%
  add_trace(
    r = c(0, 3, 3, 0),
    theta = c(0, 262.5, 277.5, 0),
    fill = 'toself',
    fillcolor = '#B6FFB4',
    line = list(
      color = 'black'
    )
  ) 
fig <- fig %>%
  layout(
    polar = list(
      radialaxis = list(
        visible = T,
        range = c(0,5)
      )
    ),
    showlegend = F
  )

fig


```

