---
title: "Health and Social Resources"
author: "Amanda E. Ljuba"
date: '2022-07-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RColorBrewer)
library(traveltime)
library(tidyverse)
library(tidycensus)
library(sf)
library(osmdata)
library(leaflet)
library(sp)
library(purrr)
library(mapview)
library(osrm)
library(rmapzen)
library(rgdal)
library(ggplot2)
library(scales)
library(nycflights13)
library(readxl)
library(leaflet.extras)
library(htmlwidgets)
```


```{r}
YourAPIKey <- "103eac37d04686a8b0104d96d983c612"
YourAppId <- "ad147923"
```

#isochrones from Sterling Elementary
```{r}
traveltime10 <- traveltime_map(appId=YourAppId,
               apiKey=YourAPIKey,
               location=c(39.009006,-77.4029155),
               traveltime=600,
               type="driving",
               departure="2022-08-09T08:00:00+01:00")
# ... and within 60 minutes?
traveltime20 <- traveltime_map(appId=YourAppId,
              apiKey=YourAPIKey,
              location=c(39.009006,-77.4029155),
              traveltime=1200,
              type="driving",
              departure="2022-08-09T08:00:00+01:00")
traveltime45 <- traveltime_map(appId = YourAppId,
                               apiKey = YourAPIKey,
                               location = c(39.009006,-77.4029155),
                               traveltime= 2700,
                               type = "driving",
                               departure = "2022-08-09T08:00:00+01:00")
```



#coordinates for Sterling Elementary
```{r}
read_excel("school_locations.xlsx")
map <- read_excel("school_locations.xlsx")
subset_map <- map[1,c(1,4,5)]
```

#ugly map
```{r}
blocks<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.04, Loudoun County, Virginia", "Block Group 2, Census Tract 6115.02, Loudoun County, Virginia","Block Group 3, Census Tract 6115.02, Loudoun County, Virginia", "Block Group 1, Census Tract 6113, Loudoun County, Virginia","Block Group 2, Census Tract 6113, Loudoun County, Virginia","Block Group 3, Census Tract 6113, Loudoun County, Virginia", "Block Group 1, Census Tract 6114, Loudoun County, Virginia","Block Group 2, Census Tract 6114, Loudoun County, Virginia","Block Group 3, Census Tract 6114, Loudoun County, Virginia","Block Group 1, Census Tract 6117.01, Loudoun County, Virginia","Block Group 2, Census Tract 6117.01, Loudoun County, Virginia", "Block Group 1, Census Tract 6116.02, Loudoun County, Virginia","Block Group 2, Census Tract 6116.02, Loudoun County, Virginia","Block Group 1, Census Tract 6116.01, Loudoun County, Virginia", "Block Group 2, Census Tract 6116.01, Loudoun County, Virginia")
va20_2 <- get_acs(geography = "block group",
                variables = c(hispanic = "B03002_012"),
                state = "VA",
                year = 2020,
                geometry = TRUE) %>%
filter(NAME %in% blocks)
leaflet(data = healthresources) %>% addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = va20_2,
color="#F0B27A",
weight = 0.5,
smoothFactor = 0.2,
fillOpacity = 0.5)  %>% 
    addPolygons(data=traveltime20, color= "#21618C",opacity = 1,weight=2,fillColor = "white", fillOpacity = .1) %>% addPolygons(data=traveltime10,color="green",opacity=1,weight=2,fillColor = "white",fillOpacity = .1) %>% addPolygons(data=traveltime45,color="#D98880",opacity = 1,weight = 2,fillColor = "white",fillOpacity = .1) %>%
  addCircleMarkers(~Longitude, ~Latitude, popup=~as.character(Name), weight = 7, radius=7, 
                 color=~cof(Resource), stroke = F, fillOpacity = 1)%>% setView(-77.4029155,39.009006, zoom = 11) %>% addLegend("bottomright",colors=c("#336600", "#0000CC","#FF0066","#FF00FF","#66FFCC","#FF6633","#996600","#FF9933","#CC3300","#99CC99"),labels = c("Food Pantry","Clothing","Medical Supplies","Counseling","Dental Care","Vision Care","Medical Services","Speech and Hearing Services","Speech Therapy","Physical Therapy"),title="Resource Type") %>% addMarkers(data = subset_map, ~Latitude,~Longitude,popup=~as.character(School),label = ~as.character(School), labelOptions = TRUE)
```

```{r}
healthsep <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx")
 popups <- lapply(
          paste("<strong>Name: </strong>",
                str_to_title(healthsep$Name),
                "<br />",
                "<strong>Description:</strong>",
                healthsep$Description ,
                "<br />",
                "<strong>Serves:</strong>",
                healthsep$Serves, 
                "<br />",
                "<strong>Hours:</strong>",
                healthsep$Hours,
                "<br />",
                "<strong>Language:</strong>",
                healthsep$Language,
                "<br />",
                "<strong>Address:</strong>",
                healthsep$Address),
                
          htmltools::HTML
        )
```

#excel with seperated health resources
```{r}
foods <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx",sheet="Food")
clothes <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx",sheet = "Clothing")
counseling <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Counseling")
dental <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Dental Care")
vision <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Vision Care")
medical <-  read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Medical Services")
speech <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Speech and Hearing")
physical <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/healthsep.xlsx", sheet = "Physical Therapy")
```





#map of health resources
```{r}
blocks<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.04, Loudoun County, Virginia", "Block Group 2, Census Tract 6115.02, Loudoun County, Virginia","Block Group 3, Census Tract 6115.02, Loudoun County, Virginia", "Block Group 1, Census Tract 6113, Loudoun County, Virginia","Block Group 2, Census Tract 6113, Loudoun County, Virginia","Block Group 3, Census Tract 6113, Loudoun County, Virginia", "Block Group 1, Census Tract 6114, Loudoun County, Virginia","Block Group 2, Census Tract 6114, Loudoun County, Virginia","Block Group 3, Census Tract 6114, Loudoun County, Virginia","Block Group 1, Census Tract 6117.01, Loudoun County, Virginia","Block Group 2, Census Tract 6117.01, Loudoun County, Virginia", "Block Group 1, Census Tract 6116.02, Loudoun County, Virginia","Block Group 2, Census Tract 6116.02, Loudoun County, Virginia","Block Group 1, Census Tract 6116.01, Loudoun County, Virginia", "Block Group 2, Census Tract 6116.01, Loudoun County, Virginia")
va20_2 <- get_acs(geography = "block group",
                variables = c(hispanic = "B03002_012"),
                state = "VA",
                year = 2020,
                geometry = TRUE) %>%
filter(NAME %in% blocks)
leaflet(data = foods) %>% addProviderTiles(providers$CartoDB.Positron) %>%
addPolygons(data = va20_2,
    color="#5f308f",
    weight = 0.5,
    smoothFactor = 0.2,
    fillOpacity = 0.5)  %>% 
addPolygons(data=traveltime20, color= "#21618C",opacity = 1,weight=2,fillColor = "white", fillOpacity = .1) %>% addPolygons(data=traveltime10,color="green",opacity=1,weight=2,fillColor = "white",fillOpacity = .1) %>%     addPolygons(data=traveltime45,color="#D98880",opacity = 1,weight = 2,fillColor = "white",fillOpacity = .1) %>%
setView(-77.4029155,39.009006, zoom = 11)%>%
addCircleMarkers(data=foods,~Longitude,~Latitude,popup=~popups,label=~as.character(Name),color="#2e850c",group = "Food",weight = 7, radius=7, 
               stroke = F, fillOpacity = 1)%>%
addCircleMarkers(data=clothes,~Longitude,~Latitude,popup=~popups,label=~as.character(Name),color=         "#0a31a5",group="Clothing",weight = 7, radius=7, 
                stroke = F, fillOpacity = 1)  %>%
addCircleMarkers(data=counseling,~Longitude,~Latitude,popup =~popups,label=~as.character(Name),color="#ec1c1c",group = "Counseling", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addCircleMarkers(data=dental,~Longitude,~Latitude,popup = ~popups,label=~as.character(Name),color="#ffd600",group = "Medical Services", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addCircleMarkers(data=vision,~Longitude,~Latitude,popup =~popups,label=~as.character(Name),color="#ffd600",group = "Medical Services", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addCircleMarkers(data=medical,~Longitude,~Latitude,popup = ~popups,label=~as.character(Name),color="#ffd600",group = "Medical Services", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addCircleMarkers(data=speech,~Longitude,~Latitude,popup =~popups,label=~as.character(Name),color="#ffd600",group = "Medical Services", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addCircleMarkers(data=physical,~Longitude,~Latitude,popup = ~popups,label=~as.character(Name),color="#ffd600",group = "Medical Services", weight = 7, radius=7, 
                stroke = F, fillOpacity = 1) %>%
addLayersControl(overlayGroups = c("Food", "Clothing", "Counseling","Medical Services")) %>% addMarkers(data=subset_map,~Longitude,~Latitude,popup = ~as.character(School)) %>% addLegend("bottomright",colors=c("green","#21618C","#D98880"),labels=c("10 minutes","20 minutes","45 minutes"),title = "Travel Time")
```

