---
title: "Mental Health Resources"
author: "Amanda E. Ljuba"
date: '2022-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RColorBrewer)
library(traveltime)
library(tidyverse)
library(tidycensus)
library(sf)
library(osmdata)
library(leaflet)
library(sp)
library(purrr)
library(mapview)
library(osrm)
library(rmapzen)
library(rgdal)
library(ggplot2)
library(scales)
library(nycflights13)
library(readxl)
library(leaflet.extras)
library(htmlwidgets)
```


```{r}
YourAPIKey <- "103eac37d04686a8b0104d96d983c612"
YourAppId <- "ad147923"
```

#isochrones from Sterling Elementary
```{r}
traveltime10 <- traveltime_map(appId=YourAppId,
               apiKey=YourAPIKey,
               location=c(39.009006,-77.4029155),
               traveltime=600,
               type="driving",
               departure="2022-08-09T08:00:00+01:00")
# ... and within 60 minutes?
traveltime20 <- traveltime_map(appId=YourAppId,
              apiKey=YourAPIKey,
              location=c(39.009006,-77.4029155),
              traveltime=1200,
              type="driving",
              departure="2022-08-09T08:00:00+01:00")
traveltime45 <- traveltime_map(appId = YourAppId,
                               apiKey = YourAPIKey,
                               location = c(39.009006,-77.4029155),
                               traveltime= 2700,
                               type = "driving",
                               departure = "2022-08-09T08:00:00+01:00")
```


#coordinates for Sterling Elementary
```{r}
read_excel("school_locations.xlsx")
map <- read_excel("school_locations.xlsx")
subset_map <- map[1,c(1,4,5)]
```

```{r}
ment <- read_excel("~/Downloads/DSPG-R-Training/2022_DSPG_Loudoun/shinyapp/data/mentalhealthres.xlsx",sheet = "Mental")
```

```{r}
 popups <- lapply(
          paste("<strong>Name: </strong>",
                str_to_title(ment$Name),
                "<br />",
                "<strong>Description:</strong>",
                ment$Description ,
                "<br />",
                "<strong>Hours:</strong>",
                ment$Hours, 
                "<br />",
                "<strong>Address:</strong>",
                ment$Address),
                
                
          htmltools::HTML
        )
```



```{r}
blocks<-c("Block Group 1, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.05, Loudoun County, Virginia", "Block Group 2, Census Tract 6112.04, Loudoun County, Virginia", "Block Group 2, Census Tract 6115.02, Loudoun County, Virginia","Block Group 3, Census Tract 6115.02, Loudoun County, Virginia", "Block Group 1, Census Tract 6113, Loudoun County, Virginia","Block Group 2, Census Tract 6113, Loudoun County, Virginia","Block Group 3, Census Tract 6113, Loudoun County, Virginia", "Block Group 1, Census Tract 6114, Loudoun County, Virginia","Block Group 2, Census Tract 6114, Loudoun County, Virginia","Block Group 3, Census Tract 6114, Loudoun County, Virginia","Block Group 1, Census Tract 6117.01, Loudoun County, Virginia","Block Group 2, Census Tract 6117.01, Loudoun County, Virginia", "Block Group 1, Census Tract 6116.02, Loudoun County, Virginia","Block Group 2, Census Tract 6116.02, Loudoun County, Virginia","Block Group 1, Census Tract 6116.01, Loudoun County, Virginia", "Block Group 2, Census Tract 6116.01, Loudoun County, Virginia")
va20_2 <- get_acs(geography = "block group",
                variables = c(hispanic = "B03002_012"),
                state = "VA",
                year = 2020,
                geometry = TRUE) %>%
filter(NAME %in% blocks)

leaflet(data = ment) %>% addProviderTiles(providers$CartoDB.Positron) %>%
addPolygons(data = va20_2,
    color="#5f308f",
    weight = 0.5,
    smoothFactor = 0.2,
    fillOpacity = 0.5)  %>% 
addPolygons(data=traveltime20, color= "#21618C",opacity = 1,weight=2,fillColor = "white", fillOpacity = .1) %>% addPolygons(data=traveltime10,color="green",opacity=1,weight=2,fillColor = "white",fillOpacity = .1) %>%     addPolygons(data=traveltime45,color="#D98880",opacity = 1,weight = 2,fillColor = "white",fillOpacity = .1) %>%
setView(-77.4029155,39.009006, zoom = 11)%>%
addCircleMarkers(data=ment,~Longitude,~Latitude,popup=~popups,label=~as.character(Name),color="#54cbd0",weight = 7, radius=7, 
               stroke = F, fillOpacity = 1)%>%
addMarkers(data=subset_map,~Longitude,~Latitude,popup = ~as.character(School)) %>% addLegend("bottomright",colors=c("green","#21618C","#D98880"),labels=c("10 minutes","20 minutes","45 minutes"),title = "Travel Time")
```