---
title: "Surveys"
author: "NDP"
date: '2022-07-12'
output: html_document
---
```{r}
library(fmsb)
newsurveydata <- read_excel(paste0(getwd(), "/NewSurveyData.xlsx"),skip=0,col_names=TRUE)
subsetnewsurveydataSTUDENT <- newsurveydata[11:16,c(1,2:6)]
```

#Student Survey Q1 - Student Engagement
```{r}
studentquestion1 <- subsetnewsurveydataSTUDENT[1:6,1:2]
question12 <- studentquestion1$SCHOOLS
studentquestion1percentage <- studentquestion1$`Question 1`
studentquestion1percentage <- as.numeric(studentquestion1percentage)
studentquestion1percentage <- studentquestion1percentage*100
twelve <- ggplot(studentquestion1,aes(x=question12,y=studentquestion1percentage,fill=question12)) +geom_col()+labs(title="Student Engagement",x="",y="Percent") + scale_fill_discrete(name = "") + geom_text(aes(label = studentquestion1percentage, y = studentquestion1percentage), size = 3, position = position_stack(vjust = 1.02))
ggplotly(twelve)
```

#Student Survey Q2 - Teacher Relationship
```{r}
studentquestion2 <- subsetnewsurveydataSTUDENT[1:6,c(1,3)]
question13 <- studentquestion2$SCHOOLS
studentquestion2percentage <- studentquestion2$`Question 2`
studentquestion2percentage <- as.numeric(studentquestion2percentage)
studentquestion2percentage <- studentquestion2percentage*100
thirteen <- ggplot(studentquestion2,aes(x=question13,y=studentquestion2percentage,fill=question13)) +geom_col()+labs(title="Teacher Relationship",x="",y="Percent") + scale_fill_discrete(name = "") + geom_text(aes(label = studentquestion2percentage, y = studentquestion2percentage), size = 3, position = position_stack(vjust = 1.02))
ggplotly(thirteen)
```

#Student Survey Q3 - Social-Emotional Wellbeing
```{r}
studentquestion3 <- subsetnewsurveydataSTUDENT[1:6,c(1,4)]
question14 <- studentquestion3$SCHOOLS
studentquestion3percentage <- studentquestion3$`Question 3`
studentquestion3percentage <- as.numeric(studentquestion3percentage)
studentquestion3percentage <- studentquestion3percentage*100
fourteen <- ggplot(studentquestion3,aes(x=question14,y=studentquestion3percentage,fill=question14)) +geom_col()+labs(title="Social-Emotional Wellbeing",x="",y="Percent") + scale_fill_discrete(name = "") + geom_text(aes(label = studentquestion3percentage, y = studentquestion3percentage), size = 3, position = position_stack(vjust = 1.02))
ggplotly(fourteen)
```

#Student Survey Q4 - Student Behavior
```{r}
studentquestion4 <- subsetnewsurveydataSTUDENT[1:6,c(1,5)]
question15 <- studentquestion4$SCHOOLS
studentquestion4percentage <- studentquestion4$`Question 4`
studentquestion4percentage <- as.numeric(studentquestion4percentage)
studentquestion4percentage <- studentquestion4percentage*100
fifteen <- ggplot(studentquestion4,aes(x=question15,y=studentquestion4percentage,fill=question15)) +geom_col()+labs(title="Student Behavior",x="",y="Percent") + scale_fill_discrete(name = "") + geom_text(aes(label = studentquestion4percentage, y = studentquestion4percentage), size = 3, position = position_stack(vjust = 1.02))
ggplotly(fifteen)
```

#Student Survey Q5 - Bullying
```{r}
studentquestion5 <- subsetnewsurveydataSTUDENT[1:6,c(1,6)]
question16 <- studentquestion5$SCHOOLS
studentquestion5percentage <- studentquestion5$`Question 5`
studentquestion5percentage <- as.numeric(studentquestion5percentage)
studentquestion5percentage <- studentquestion5percentage*100
sixteen <- ggplot(studentquestion5,aes(x=question16,y=studentquestion5percentage,fill=question16)) +geom_col()+labs(title="Bullying",x="",y="Percent") + scale_fill_discrete(name = "") + geom_text(aes(label = studentquestion5percentage, y = studentquestion5percentage), size = 3, position = position_stack(vjust = 1.02))
ggplotly(sixteen)
```
